# Generated by Django 3.2.4 on 2021-06-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_compradetalle_comprasenc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprasenc',
            old_name='fecha_compre',
            new_name='fecha_compra',
        ),
    ]
