# Generated by Django 3.2.4 on 2021-06-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_auto_20210616_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo_barra',
            field=models.CharField(max_length=13),
        ),
    ]
